# # config/features.yml


columns:
  "sdrf.stimulus":
    regex: "stimulus\t\\a*\\t"
    target_table: Stimuli
    target_column: label
    transforms:
      - get_iri
      - get_chem_class

  "obs.organism":
    regex: "[A-Z][a-z]+ [a-z]+"
    target_table: Taxa
    target_column: species_name
    transforms:
      - get_iri
      - get_ranking

  "obs.organism_ontology_term_id":
    regex: "[A-Za-z]+:\\d+"
    target_table: Taxa
    target_column: iri
    transforms:
      - get_name
      - get_ranking

  "var.gene_id":
    regex: "ENS[A-Z]*G\\d{5,}"
    target_table: Genes
    target_column: gene_id
    transforms:
      - canonical_iri
      - strip_version
      - get_name

  "sdrf.cell type":
    regex: "cell type\\t"
    target_table: Samples
    target_column: cell_type_id
    transforms:
      - get_iri
      - get_ontology

  "obs.cell_type_ontology_term_id":
    regex: "CL:\\d{7}"
    target_table: Samples
    target_column: cell_type_id
    transforms:
      - get_name
      - get_ontology

  "obs.tissue_ontology_term_id":
    regex: "UBERON:\\d+"
    target_table: Samples
    target_column: tissue_id
    transforms:
      - get_name
      - get_ontology

  "obs.suspension_type":
    regex: "[A-Za-z]+(?: [A-Za-z]+)*"
    target_table: Samples
    target_column: growth_condition
    transforms: []

  "sdrf.growth condition":
    regex: "(?:mono|co)-culture"
    target_table: Samples
    target_column: growth_condition
    transforms: []

  "obs.sample_id":
    regex: "[A-Za-z0-9_-]+"
    target_table: Samples
    target_column: sample_id
    transforms:
      - get_local_link