# config/features.yml
meta:
  - stimulus_id
  - iri
  - label
  - class_hint
  - microbe_id
  - taxon_id
  - species_name
  - evidence
  - study_id
  - title
  - source_repo
  - sample_id
  - cell_type_iri
  - cell_type_label
  - tissue_iri
  - tissue_label
  - organism_iri
  - organism_label
  - growth_condition
  - zarr_uri
  - log2_fc
  - p_value
  - significance

genes:
  - gene_id
