# conf/mapping_catalogue.yml  (excerpt)

columns:
  gene_id:
    regex: "^[Ee][Nn][Ss][Gg]\\d{11}(?:\\.\\d+)?$"
    target_table: Genes
    target_column: gene_id
    transforms:
      - strip_version
      - harmonize_to_ensembl
      - extract_gene_id

  gs_symbol:
    regex: "^[A-Z0-9]{2,}$"
    target_table: Genes
    target_column: gene_name
    transforms: []

  stimulus:
    regex: "(?<=\\b(?:characteristic|factor)\\s+stimulus\\s+)(.*?)(?=\\s+http)"                # free-text; normalised later
    target_table: Stimuli
    target_column: label
    transforms:
      - lowercase_ascii
      - resolve_stimulus_iri

  # ── Cell-type ontology IDs ────────────────────────────────────────────
  cell_type_ontology_term_id:               # CL terms (full IRI or short form)
    regex: "^(?:https?://.*obo/)?CL[:_]\\d+$"
    target_table: Samples
    target_column: cell_type_iri
    transforms:
      - canonical_iri

  assay_ontology_term_id:           # EFO cell-line / sample terms
    regex: "^(?:https?://.*obo/)?EFO[:_]\\d+$"
    target_table: Samples
    target_column: cell_type_iri
    transforms:
      - canonical_iri

    # ── Anatomical / developmental context ───────────────────────────────
  tissue_ontology_term_id:
    # e.g. UBERON:0009834  or  http://purl.obolibrary.org/obo/UBERON_0009834
    regex: "^(?:https?://.*obo/)?UBERON[:_]\\d+$"
    target_table: Samples
    target_column: tissue_iri
    transforms:
      - split_commas            # splits into list
      - canonical_iri

  development_stage_ontology_term_id:
    # e.g. HsapDv:0000095
    regex: "^(?:https?://.*obo/)?HsapDv[:_]\\d+$"
    target_table: Samples
    target_column: development_stage_iri        # add this column if it doesn’t exist yet
    transforms:
      - split_commas            # splits into list
      - canonical_iri

  # ── Health / disease state ───────────────────────────────────────────
  disease_ontology_term_id:
    # accepts either MONDO or PATO disease-quality terms
    regex: "^(?:https?://.*obo/)?(?:MONDO|PATO)[:_]\\d+$"
    target_table: Samples
    target_column: disease_iri                  # add this column if needed
    transforms:
      - split_commas            # splits into list
      - canonical_iri

  # ── Organism provenance ─────────────────────────────────────────────
  organism_ontology_term_id:
    # e.g. NCBITaxon:9606  (human)
    regex: "^(?:https?://.*obo/)?NCBITaxon[:_]\\d+$"
    target_table: Samples
    target_column: organism_iri                 # re-uses the column already in schema
    transforms:
      - canonical_iri

  # ── Donor metadata ──────────────────────────────────────────────────
  self_reported_ethnicity_ontology_term_id:
    # one or more HANCESTRO IDs separated by commas
    regex: "^(?:https?://.*obo/)?HANCESTRO[:_]\\d+(?:,\\s*HANCESTRO[:_]\\d+)*$"
    target_table: Samples
    target_column: ethnicity_iris               # create as JSON/text array if multiple values
    transforms:
      - split_commas            # splits into list
      - canonical_iri       # runs on each element

  sex_ontology_term_id:
    # PATO sex terms:  PATO:0000383 (female), PATO:0000384 (male)
    regex: "^(?:https?://.*obo/)?PATO[:_]\\d+$"
    target_table: Samples
    target_column: sex_iri                      # add this column if needed
    transforms:
      - canonical_iri
