# # conf/mapping_catalogue.yml  (excerpt)

version: 2
columns:

  # ------------------------------------------------------------------------
  # Genes table  (gene_id, gene_name)
  # ------------------------------------------------------------------------
  gene_entry:
    regex: "(ENS[A-Z]*G\\d{5,})"
    transforms:
      # - extract_gene_id            # scalar → ENSG…
      - strip_version
      - harmonize_to_ensembl       # dict  → {gene_id, gene_name}
    target_table: Genes
    target_column: gene_id

  # ------------------------------------------------------------------------
  # Stimuli table  (iri, label, class_hint)
  # ------------------------------------------------------------------------
  stimulus_entry:
    regex: "(CHEBI:\\d+|EFO:\\d+|TNFα|butyrate|none)"
    transforms:
      - canonical_iri               # scalar → full IRI
      - fetch_stimulus_metadata    # dict   → {iri, label, class_hint}
    target_table: Stimuli
    target_column: iri

  # ------------------------------------------------------------------------
  # Microbes table  (taxon_id, species_name)
  # ------------------------------------------------------------------------
  microbe_entry:
    regex: "NCBITaxon:\\d+"
    transforms:
      - fetch_from_ncbi_taxon      #extract_taxon_numeric_id   # scalar → 816 (int)
      - fetch_microbe_metadata     # dict   → {taxon_id, species_name}
    target_table: Microbes
    target_column: taxon_id

  # ------------------------------------------------------------------------
  # Studies table  (study_id, title, source_repo)
  # ------------------------------------------------------------------------
  study_accession:
    regex: "(E-MTAB-\\d+|GSE\\d+|LOCAL-[A-Za-z0-9_-]+)"
    transforms:
      - normalize_study_accession  # scalar → canonical study_id
      - fetch_study_metadata       # dict   → {study_id, title, source_repo}
    target_table: Studies
    target_column: study_id

  # ------------------------------------------------------------------------
  # Samples table  (wide metadata payload)
  # ------------------------------------------------------------------------
  sample_accession:
    regex: "(SAM[END]\\d+|SRS\\d+|SAMPLE_[A-Za-z0-9_-]+)"
    transforms:
      - extract_sample_id          # scalar → sample_id
      - fetch_sample_metadata      # dict   → {
                                      # sample_id,
                                      # study_id,
                                      # cell_type_iri, cell_type_label,
                                      # tissue_iri, tissue_label,
                                      # organism_iri, organism_label,
                                      # growth_condition,
                                      # stimulus_id, microbe_id,
                                      # zarr_uri
                                      # }
    target_table: Samples
    target_column: sample_id

  # ------------------------------------------------------------------------
  # MicrobeStimulus link‑table  (microbe_id, stimulus_id, evidence)
  # ------------------------------------------------------------------------
  microbe_stimulus_evidence:
    regex: "NCBITaxon:\\d+.*(CHEBI:\\d+|EFO:\\d+)"
    transforms:
      - parse_microbe_stimulus_record   # dict → {microbe_id, stimulus_id, evidence}
    target_table: MicrobeStimulus
    target_column: microbe_id

  # ------------------------------------------------------------------------
  # ExpressionStats table  (sample_id, gene_id, log2_fc, p_value, significance)
  # ------------------------------------------------------------------------
  expression_stat_record:
    regex: "exprstat:.*"                # adjust to your extractor’s tag
    transforms:
      - parse_expression_stat_record    # dict → {sample_id, gene_id, log2_fc, p_value, significance}
    target_table: ExpressionStats
    target_column: sample_id


# ---------------------------------------------------------------------------
# AVAILABLE TRANSFORM OPERATORS
# ---------------------------------------------------------------------------
# Below is a complete list of all functions that are referenced here, in mapping_catalogue.yml:
#
# • extract_gene_id(text: str) -> str
#   └── Plucks the first Ensembl gene ID (ENS…)
# • harmonize_to_ensembl(gene_id: str) -> dict
#   └── Enriches gene_id via MyGene.info → {gene_id, gene_name}
# • canonical_iri(curie_or_label: str) -> str
#   └── Expands CURIEs (CHEBI:, EFO:, etc.) to full IRIs
# • curie_to_iri = canonical_iri
# • fetch_stimulus_metadata(iri: str) -> dict
#   └── Queries EMBL‑EBI OLS → {iri, label, class_hint}
# • extract_taxon_numeric_id(curie: str) -> int | None
#   └── Parses NCBITaxon:NNN → NNN
# • fetch_from_ncbi_taxon = extract_taxon_numeric_id
# • fetch_microbe_metadata(taxon_id: int) -> dict
#   └── NCBI Taxonomy API lookup → {taxon_id, species_name}
# • normalize_study_accession(acc: str) -> str
#   └── Trims/canonicalizes study accession strings
# • fetch_study_metadata(study_id: str) -> dict
#   └── Fetches title/source from ArrayExpress or GEO
# • extract_sample_id(text: str) -> str
#   └── Pass-through sample accession
# • fetch_sample_metadata(sample_id: str) -> dict
#   └── Merges metadata from BioSamples, SRA, or local CXG JSON
# • parse_microbe_stimulus_record(text: str) -> dict
#   └── Parses JSON, TSV, or free‑text → {microbe_id, stimulus_id, evidence}
# • parse_expression_stat_record(text: str) -> dict
#   └── Parses legacy or TSV exprstat rows → {sample_id, gene_id, log2_fc, p_value, significance}